cmd/jaeger-clickhouse/main.go, config.yaml, embed.go, storage/store.go
=> Embed scripts into binary

.github/workflows/release.yaml, Makefile, RELEASE.md
=> Configure release

Makefile, README.md, config.yaml
=> Use docker to run example

Makefile, cmd/jaeger-clickhouse/main.go, jaeger-ui.json, sqlscripts/0004-jaeger-spans-archive.sql, storage/store.go
=> Add support for archive storage

Makefile, README.md, cmd/jaeger-clickhouse/main.go, config.yaml, storage/config.go, storage/store.go
Enables connection to remote databases with various settings.
This is properly done version of my previous pull request.
Resolves #18
=> Add auth support

.gitignore, Makefile, cmd/jaeger-clickhouse/main.go, config.yaml, go.mod, go.sum, storage/clickhousespanstore/writer.go, storage/config.go
Closes https://github.com/pavolloffay/jaeger-clickhouse/issues/19
Adds metrics for batch size and flush interval along with their count in prometheus exposition format.
Signed-off-by: Pradeep Chhetri <pradeepchhetri4444@gmail.com>
=> Expose metrics

README.md
Returned to previous makefile phonies & cahnged README a bit
=> Fixed Makefile & edited README

sqlscripts/0001-jaeger-index.sql, sqlscripts/0002-jaeger-spans.sql, sqlscripts/0003-jaeger-operations.sql, sqlscripts/0004-jaeger-spans-archive.sql, storage/store.go
=> Remove v2 suffix from table names

README.md, guide-multitenancy.md
Resolves #29 
Using separate tables per tenant should help with data removal/TTL per tenant.
The question is if there is any limit on the number of databases or if the databases allocate some system resources which would make a database per tenant inefficient.
=> Document multitenancy

guide-sharding-and-replication.md
=> Use replication without arguments

guide-sharding-and-replication.md
=> Document scaling

storage/clickhousespanstore/mocks/spylogger.go, storage/clickhousespanstore/mocks/spylogger_test.go
Also implemented SpyLogger.Name()
=> Added tests for SpyLogger

storage/clickhousespanstore/mocks/converter_test.go
100% coverage for conveter mock now
=> Added tests for unsupported types in converter mock

config.yaml
=> Document how database works

config.yaml, guide-sharding-and-replication.md
=> Document that replication does not work on default databse

config.yaml, sqlscripts/local/0001-jaeger-index.sql, sqlscripts/local/0002-jaeger-spans.sql, sqlscripts/local/0003-jaeger-operations.sql, sqlscripts/local/0004-jaeger-spans-archive.sql, sqlscripts/replication/0001-jaeger-index-local.sql, sqlscripts/replication/0002-jaeger-spans-local.sql, sqlscripts/replication/0003-jaeger-operations-local.sql, sqlscripts/replication/0004-jaeger-spans-archive-local.sql, storage/config.go, storage/store.go
=> Adding native support for TTL in tables

config.yaml, sqlscripts/local/0001-jaeger-index.sql, sqlscripts/local/0003-jaeger-operations.sql, sqlscripts/replication/0001-jaeger-index-local.sql, sqlscripts/replication/0003-jaeger-operations-local.sql, storage/clickhousespanstore/reader.go, storage/clickhousespanstore/reader_test.go, storage/clickhousespanstore/writer.go, storage/clickhousespanstore/writer_test.go
=> Added support for SpanKind in operations

blog/post1.md
Signed-off-by: Yury Frolov <yura200253@gmail.com>
=> Fixed typo in blog post

.github/workflows/build.yaml, .github/workflows/release.yaml
Signed-off-by: Yury Frolov <yura200253@gmail.com>
=> Changed go version in workflows to 1.17

storage/clickhousespanstore/heap.go, storage/clickhousespanstore/params.go, storage/clickhousespanstore/pool.go, storage/clickhousespanstore/worker.go
Added comments for WriteWorker, WriteWorkerPool & workerHeap.
Signed-off-by: Yury Frolov <yura200253@gmail.com>
=> Added comments for new types

config.yaml, storage/clickhousespanstore/pool.go, storage/clickhousespanstore/writer.go, storage/config.go, storage/config_test.go, storage/store.go, storage/store_test.go
- Resolves #95 
- Added maxSpanCount parameter to config file;
- This parameter is given to WriteWorkerPool.
=> Add max span count parameter

sqlscripts/replication/0003-jaeger-operations-local.sql
The table engine of operation is wrong and the query is very slow.
- Update the table engine of replication to be the same as the local table engine.
=> fix replication operation table engine
